p2/base/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.bienvenida, name="bienvenida"),
    path('listacursos/', views.listacursos, name="listacursos"),
    path('crear-curso/', views.crearCurso, name="crear-curso"),
    path('actualizar-curso/<str:pk>/', views.actualizarCurso, name="actualizar-curso"),
    path('eliminar-curso/<str:pk>/', views.eliminarCurso, name="eliminar-curso"),
    path('curso/<str:pk>', views.curso, name="curso"),
    path('crear-estudiante/<str:pk>', views.crearEstudiante, name="crear-estudiante"),
    path('actualizar-estudiante/<str:pk>/', views.actualizarEstudiante, name="actualizar-estudiante"),
    path('eliminar-estudiante/<str:pk>/', views.eliminarEstudiante, name="eliminar-estudiante"),
    path('prueba/', views.prueba, name="prueba"),
    path('crear-prueba/', views.crearPrueba, name="crear-prueba"),
    path('actualizar-prueba/<str:pk>/', views.actualizarPrueba, name="actualizar-prueba"),
    path('eliminar-prueba/<str:pk>/', views.eliminarPrueba, name="eliminar-prueba"),
    path('preguntas/<str:pk>', views.preguntas, name="preguntas"),
]

p2/p2/urls.py
from django.contrib import admin
from django.urls import path, include 
import debug_toolbar

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls')),
    path('__debug__', include(debug_toolbar.urls)),
]

p2/base/models.py
from django.db import models
from django.contrib.auth.models import User

class Prueba(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    nombre_prueba = models.CharField('Nombre Prueba', max_length=100)

    def __str__(self):
        return str(self.id) + '-' + self.nombre_prueba

class Tema(models.Model):
    nombre_tema = models.CharField('Nombre Tema', max_length=100)

    def __str__(self):
        return str(self.id) + '-' + self.nombre_tema

class Preguntas(models.Model):
    prueba = models.ForeignKey(Prueba, on_delete=models.CASCADE)
    tema = models.ForeignKey(Tema, on_delete=models.CASCADE)

    pregunta = models.CharField('Pregunta', max_length=100)
 
    def __str__(self):
        return str(self.id) + '-' + self.pregunta

class Curso(models.Model):
    nombre_curso = models.CharField('Nombre del Curso', max_length=100)

    def __str__(self):
        return self.nombre_curso        

class Estudiante(models.Model):
    curso = models.ForeignKey(Curso, on_delete=models.CASCADE)

    nombres = models.CharField('Nombres', max_length=20)
    apellidos = models.CharField('Apellidos', max_length=20)
    nombre_completo = models.CharField('Nombre Completo', max_length=40, blank=True)
    
    preguntas = models.ManyToManyField(Preguntas,through='EstudiantePreguntas', blank=True)

    #class Meta:
    #    verbose_name = 'Estudiante'
    #    verbose_name_plural = 'Estudiantes del curso'
    #    ordering = ['-nombres', 'apellidos']

    def __str__(self):
        return self.nombres + ' ' + self.apellidos

class EstudiantePreguntas(models.Model):
    estudiante = models.ForeignKey(Estudiante, on_delete=models.CASCADE, blank=True, null=True)
    preguntas = models.ForeignKey(Preguntas, on_delete=models.CASCADE, blank=True, null=True)

    correcto = models.BooleanField(null=True)

    def __str__(self):
        return str(self.id) + '-' + self.estudiante.nombres

p2/login/models.py
from django.db import models

# Create your models here.

p2/base/forms.py
from django.forms import ModelForm
from .models import Curso, Estudiante, Prueba

class CursoForm(ModelForm):
    class Meta:
        model = Curso
        fields = '__all__'

class EstudianteForm(ModelForm):
    class Meta:
        model = Estudiante
        fields = '__all__'

class PruebaForm(ModelForm):
    class Meta:
        model = Prueba
        fields = '__all__'

p2/base/views.py
from django.shortcuts import render, redirect
from .models import Curso, Estudiante, Preguntas, Prueba
from .forms import CursoForm, EstudianteForm, PruebaForm

def bienvenida(request):
    return render(request, 'base/bienvenida.html')

def listacursos(request):
    cursos = Curso.objects.all()
    context = {'cursos': cursos}
    return render(request, 'base/listacursos.html', context)

def crearCurso(request):
    form = CursoForm()
    if request.method == 'POST':
        form = CursoForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('listacursos')
    context = {'form': form}
    return render(request, 'base/curso_form.html', context)

def actualizarCurso(request, pk):
    curso = Curso.objects.get(id=pk)
    form = CursoForm(instance=curso)
    if request.method == 'POST':
        form = CursoForm(request.POST, instance=curso)
        if form.is_valid():
            form.save()
            return redirect('listacursos')
    context = {'form': form}
    return render(request, 'base/curso_form.html', context)

def eliminarCurso(request, pk):
    curso = Curso.objects.get(id=pk)
    if request.method == 'POST':
        curso.delete()
        return redirect('listacursos')
    return render(request, 'base/delete.html', {'obj':curso})

def curso(request, pk):
    curso = Curso.objects.get(id=pk)
    context = {'curso': curso}
    return render(request, 'base/curso.html', context)

def crearEstudiante(request, pk):
    curso = Curso.objects.get(id=pk)
    context = {'curso': curso}
    form = EstudianteForm()
    if request.method == 'POST':
        form = EstudianteForm(request.POST)
        if form.is_valid():
            form.save()
            return render(request, 'base/curso.html', context)
    context = {'form': form}
    return render(request, 'base/curso_form.html', context)

def actualizarEstudiante(request, pk):
    estudiante = Estudiante.objects.get(id=pk)
    form = EstudianteForm(instance=estudiante)
    if request.method == 'POST':
        form = EstudianteForm(request.POST, instance=estudiante)
        if form.is_valid():
            form.save()
            return redirect('listacursos')
    context = {'form': form}
    return render(request, 'base/curso_form.html', context)

def eliminarEstudiante(request, pk):
    estudiante = Estudiante.objects.get(id=pk)
    if request.method == 'POST':
        estudiante.delete()
        return redirect('listacursos')
    return render(request, 'base/delete.html', {'obj':estudiante})

def prueba(request):
    pruebas = Prueba.objects.all()
    context = {'pruebas': pruebas}
    return render(request, 'base/prueba.html', context)

def crearPrueba(request):
    form = PruebaForm()
    if request.method == 'POST':
        form = PruebaForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('prueba')
    context = {'form': form}
    return render(request, 'base/curso_form.html', context)

def actualizarPrueba(request, pk):
    prueba = Prueba.objects.get(id=pk)
    form = PruebaForm(instance=prueba)
    if request.method == 'POST':
        form = PruebaForm(request.POST, instance=prueba)
        if form.is_valid():
            form.save()
            return redirect('prueba')
    context = {'form': form}
    return render(request, 'base/curso_form.html', context)

def eliminarPrueba(request, pk):
    prueba = Prueba.objects.get(id=pk)
    if request.method == 'POST':
        prueba.delete()
        return redirect('prueba')
    return render(request, 'base/delete.html', {'obj':prueba})  

def preguntas(request, pk):
    preguntas = Preguntas.objects.get(id=pk)
    context = {'preguntas': preguntas}
    return render(request, 'base/preguntas.html', context)

p2/login/views.py
from django.shortcuts import render

# Create your views here.

p2/base/templates/base/bienvenida.html
{% extends 'base/main.html' %}

{% block content %}
<html>
    <body>
        <!-- {% if user.is_authenticated %}
        <h1>Hola {{ user.first_name }}!</h1>
        {% else %}
        <h1>Hola usuario!</h1>
        {% endif %}        -->
         
    </body>
</html>
{% endblock content %}

p2/base/templates/base/curso.html
{% extends 'base/main.html' %}

{% block content %}

<h1>{{curso.nombre_curso}}</h1>
<div>
    <a href="{% url 'crear-estudiante' curso.id %}">Añadir estudiante</a>
    <div>
        {% for estudiante in curso.estudiante_set.all %}
            <div>
                <h3><a href="{% url 'actualizar-estudiante' estudiante.id %}">{{estudiante.nombres}} {{estudiante.apellidos}}</a></h3>
                <a href="{% url 'eliminar-estudiante' estudiante.id %}">Eliminar estudiante</a>     
            </div>
        {% empty %}
            No existe aún ningún estudiante relacionado al curso.
        {% endfor %}
    </div>
</div>
{% endblock content %}

p2/base/templates/base/curso_form.html
{% extends 'base/main.html' %}

{% block content %}

<div>
    <form method="POST" action="">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="Enviar">
    </form>
</div>

{% endblock content %}

p2/base/templates/base/delete.html
{% extends 'base/main.html' %}

{% block content %}

<form method="POST" action="">
    {% csrf_token %}
    <p>Estás seguro que quieres eliminar a "{{obj}}"?</p>
    <a href="{{request.META.HTTP_REFERER}}">Volver</a>
    <input type="submit" value="Confirmar">
</form>

{% endblock content %}

p2/base/templates/base/listacursos.html
{% extends 'base/main.html' %}

{% block content %}

<h1>Cursos</h1>
<div>
    <a href="{% url 'crear-curso' %}">Crear curso</a>
    <div>
        {% for curso in cursos %}
            <div>
                <h3><a href="/curso/{{curso.id}}">{{curso.nombre_curso}}</a></h3>
                <a href="{% url 'actualizar-curso' curso.id %}">Actualizar curso</a>   
                <a href="{% url 'eliminar-curso' curso.id %}">Eliminar curso</a>           
                <!-- <h3>{{curso.id}} -- <a href="{% url 'curso' curso.id %}">{{curso.nombre_curso}}</a></h3> -->
            </div>
        {% empty %}
            No existe aún ningún curso añadido.
            <a href="{% url 'crear-curso' %}">Crear curso</a>
        {% endfor %}
    </div>
</div>

{% endblock content %}

p2/base/templates/base/main.html
<!DOCTYPE html>
<html>
<head>
    <meta charset='utf-8'>
    <meta http-equiv='X-UA-Compatible' content='IE=edge'>
    <title>Analisis de rendimiento</title>
    <meta name='viewport' content='width=device-width, initial-scale=1'> 
</head>
<body>
    {% include 'base/navbar.html' %}
    
    {% block content %}

    {% endblock %}
    
</body>
</html>

p2/base/templates/base/navbar.html
<div>        
    {% if user.is_authenticated %}
        <h3>Hola profesor {{ user.first_name }}!</h3>
    {% else %}
        <h3>Hola usuario!</h3>
    {% endif %}       
</div>
<div>
    <a href="/">Bienvenida</a>
    <a>...</a>
    <a href="{% url 'listacursos' %}">Ver lista de los cursos </a>
    <a>...</a>
    <a href="{% url 'prueba' %}">Ver pruebas añadidas</a>
    <a>...</a>
    {% if request.user.is_authenticated %}
        <a href="/logout">Cerrar sesión</a>    
    {% else %}
        <a href="/login">Iniciar sesión</a>   
    {% endif %}
</div>

p2/base/templates/base/preguntas.html
{% extends 'base/main.html' %}

{% block content %}

<div>
    <div>
        {% for preguntas in prueba.preguntas_set.all %}
            <div>
                <h3>{{preguntas.pregunta}}</h3>
            </div>
        {% empty %}
            No existe aún ninguna pregunta relacionado a la prueba.
        {% endfor %}
    </div>
</div>
{% endblock content %}

p2/base/templates/base/prueba.html
{% extends 'base/main.html' %}

{% block content %}

<h1>Pruebas</h1>
<div>
    <a href="{% url 'crear-prueba' %}">Añadir prueba</a>
    <div>
        {% for prueba in pruebas %}
            <div>
                <h3><a href="/preguntas/{{prueba.id}}">{{prueba.nombre_prueba}}</a></h3>
                <a href="{% url 'actualizar-prueba' prueba.id %}">Actualizar prueba</a> 
                <a href="{% url 'eliminar-prueba' prueba.id %}">Eliminar prueba</a>     
            </div>
        {% empty %}
            No existe aún ninguna prueba añadida.
        {% endfor %}
    </div>
</div>
{% endblock content %}